routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('');


Route::get('/students/show_deleted', [App\Http\Controllers\StudentController::class, 'show_deleted'])->name('students.show_deleted');
Route::put('/students/restore/{student}', [App\Http\Controllers\StudentController::class, 'restore'])->name('students.restore')->withTrashed();
Route::resource('/students', App\Http\Controllers\StudentController::class);


Route::resource('/courses', App\Http\Controllers\CourseController::class);

Route::get('/attendances/show_deleted', [App\Http\Controllers\AttendanceController::class, 'show_deleted'])->name('attendances.show_deleted');
Route::put('/attendances/restore/{attendances}',[App\Http\Controllers\AttendanceController::class, 'restore'])->name('attendances.restore')->withTrashed();
Route::resource('/attendances', App\Http\Controllers\AttendanceController::class);



Route::get('/learndays/show_deleted', [App\Http\Controllers\LearnDayController::class, 'show_deleted'])->name('learndays.show_deleted');
Route::put('/restore_learndays/{learndays}', [App\Http\Controllers\LearnDayController::class, 'restore'])->name('learndays.restore')->withTrashed();
Route::resource('/learndays', App\Http\Controllers\LearnDayController::class);

app/Models/Attendance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Attendance extends Model
{
    use HasFactory;
    /* use SoftDeletes; */


    protected $fillable = [
        'status',
        'learn_days_id',
        'student_id'
    ];

    
    public function student():BelongsTo
    {
        return $this->belongsTo(Student::class);
    }
    

    public function learnday(): BelongsTo
    {
        return $this->belongsTo(LearnDay::class, 'learn_days_id', 'id');
    }
}

app/Http/Controllers/AttendanceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreAttendanceRequest;
use App\Http\Requests\UpdateAttendanceRequest;
use App\Models\Attendance;
use App\Models\LearnDay;

class AttendanceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $attendances = Attendance::all();
        return view("attendances.index", ['attendances' => $attendances]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store($learnday)
    {
        
    }

    /**
     * Display the specified resource.
     */
    public function show(Attendance $attendance)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Attendance $attendance)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateAttendanceRequest $request, Attendance $attendance)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Attendance $attendance)
    {
        //
    }
}

resources/views/attendances/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-5">
        <div class="col-2"></div>
        <div class="col-8">
            @if (Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                    <strong>Holy guacamole!</strong>
                    <p>{{ Session::get('success') }}</p>
                </div>
            @endif
            <div class="table-responsive-xl">
                <table class="table table-dark" id="studentTable">
                    <thead>
                        <tr>
                            <th scope="col">Student name</th>
                            <th scope="col">Attendance status</th>
                            <th></th>
                            <th scope="col">Actions</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($attendances as $item)
                            <tr class="">
                                <td scope="row">{{ $item->student->name }}</td>
                                <td>{{$item->status}}</td>
                                {{-- {{ dd($item->learnday()->get) }} --}}
                                {{-- {{ dd( $item->learnday->date) }} --}}
                                <td>{{$item->learnday->date}}</td>
                                <td>
                                    <form action="{{ route('attendances.edit', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-warning">Edit</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ route('attendances.destroy', $item) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                                <td>

                                    <form action="{{ route('attendances.show', $item) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-info">Show data</button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>

@endsection