routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('');


Route::get('/students/show_deleted', [App\Http\Controllers\StudentController::class, 'show_deleted'])->name('students.show_deleted');
Route::put('/students/restore/{student}', [App\Http\Controllers\StudentController::class, 'restore'])->name('students.restore')->withTrashed();
Route::resource('/students', App\Http\Controllers\StudentController::class);


Route::resource('/courses', App\Http\Controllers\CourseController::class);

Route::get('/attendances/show_deleted', [App\Http\Controllers\AttendanceController::class, 'show_deleted'])->name('attendances.show_deleted');
Route::put('/attendances/restore/{attendances}',[App\Http\Controllers\AttendanceController::class, 'restore'])->name('attendances.restore')->withTrashed();
Route::resource('/attendances', App\Http\Controllers\AttendanceController::class);



Route::get('/learndays/show_deleted', [App\Http\Controllers\LearnDayController::class, 'show_deleted'])->name('learndays.show_deleted');
Route::put('/restore_learndays/{learndays}', [App\Http\Controllers\LearnDayController::class, 'restore'])->name('learndays.restore')->withTrashed();
Route::resource('/learndays', App\Http\Controllers\LearnDayController::class);

app/Models/LearnDay.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class LearnDay extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'title',
        'date',
        'course_id'
    ];


    public function course(): BelongsTo
    {
        return $this->belongsTo(Course::class);
    }

    public function attendances():HasMany
    {
        return $this->hasMany(Attendance::class);
    }
}

app/Http/Controllers/LearnDayController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreLearnDayRequest;
use App\Http\Requests\UpdateLearnDayRequest;
use App\Models\Course;
use App\Models\LearnDay;
use App\Models\Student;

class LearnDayController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $learndays = LearnDay::all();
        return view("learndays.index", ['learndays' => $learndays]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(LearnDay $learnday)
    {
        $courses = Course::all();
        return view('learndays.create' , ['learndays' => $learnday, 'courses' => $courses]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreLearnDayRequest $request)
    {
        $learnday = new LearnDay(
            [
                "title" => $request->title,
                "date" => $request->date,
                "course_id" => $request->course_id
            ]
        );

        $learnday->save();

        return redirect()->route('attendances.store', $learnday);
    }

    /**
     * Display the specified resource.
     */
    public function show( $learnDay)
    {
        $learnDay = LearnDay::find($learnDay);
        return view('learndays.show', ['learndays' => $learnDay ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($learnDay)
    {
        $courses = Course::all();

        $learnDay = LearnDay::find($learnDay);
        return view('learndays.edit', ['learndays' => $learnDay, 'courses' => $courses]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateLearnDayRequest $request, LearnDay $learnday)
    {
        
        $learnday->update($request->all());

        return redirect()->route('learndays.index')->with('success', 'The learn day was updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy( $learnDay)
    {

        $learnDay = LearnDay::find($learnDay);
        $learnDay->delete();
        return back()->with('success', 'Successfully deleted the learn day: ' . $learnDay->title . '.');
    }


    public function show_deleted()
    {
        $deleted_days = LearnDay::onlyTrashed()->get();
        return view('learndays.show_deleted', ['learndays' => $deleted_days]);
    }

    public function restore($learnDay)
    {
        $learnDay = LearnDay::withTrashed()->find($learnDay);
        $learnDay->restore();
        return back()->with('success', '' . $learnDay->title . ' was successfully restored.');
    }

}

resources/views/learndays/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card border-secondary bg-dark">
                <div class="card-body text-white">
                    <h4 class="card-title">Add a Learn Day</h4>
                    <p class="card-text text-danger">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif

                    <form action="{{ route('learndays.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('POST')
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" name="title" id="title" class="form-control @if($errors->has('title')) border border-danger @endif"
                                placeholder="Title of the Day" aria-describedby="helpId" value="{{old('title')}}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                            @else
                                <small id="helpId" class="text-white">The name of the Title must be added.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="date" class="form-label">Date</label>
                            <input type="date" name="date" id="date" class="form-control"
                                placeholder="0000-00-00" aria-describedby="helpId" maxlength="255">
                            <small id="helpId" class="text-white">Date of the Learn Day</small>
                        </div>
                        <div class="mb-3">
                            <label for="course" class="form-label">Class</label>
                            <select class="form-select" aria-label="Default select example" name="course_id">
                                <option hidden>Classes</option>
                                @foreach ($courses as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                            <small id="helpId" class="text-white">For which class the Learn Day is</small>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/learndays/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col"></div>
        <div class="col">
            <div class="card border-secondary bg-dark">
                <div class="card-body text-white">
                    <h4 class="card-title">Edit a Learn Day named: {{ $learndays->title }}</h4>
                    <p class="card-text text-danger">Inputs marked with * shall be filled.</p>

                    @if ($errors->any())
                        <div class="mb-3 mt-3">
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                                <strong>Holy guacamole!</strong>

                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    @endif

                    @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                            <strong>Holy guacamole!</strong>
                            <p>{{ Session::get('success') }}</p>
                        </div>
                    @endif

                    <form action="{{ route('learndays.update', $learndays ) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" name="title" id="title"
                                class="form-control @if ($errors->has('title')) border border-danger @endif"
                                placeholder="Title of the Day" aria-describedby="helpId"
                                value="{{ old('title', $learndays->title) }}">

                            @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('title') }}</small>
                            @else
                                <small id="helpId" class="text-white">The name of the course to be created.</small>
                            @endif

                        </div>
                        <div class="mb-3">
                            <label for="date" class="form-label">Date</label>
                            <input type="date" name="date" id="date" class="form-control"
                                placeholder="0000-00-00" aria-describedby="helpId" maxlength="255"
                                value="{{ old('date', $learndays->date) }}">
                            <small id="helpId" class="text-white">Date of the Learn Day</small>
                        </div>
                        <div class="mb-3">
                            <label for="course" class="form-label">Class</label>
                            <select class="form-select" aria-label="Default select example" name="course_id">
                                <option hidden>Classes</option>
                                @foreach ($courses as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                            <small id="helpId" class="text-white">For which class the learn day is</small>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>

@endsection

resources/views/learndays/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row mt-5">
        <div class="col-2"></div>
        <div class="col-8">
            @if (Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

                    <strong>Holy guacamole!</strong>
                    <p>{{ Session::get('success') }}</p>
                </div>
            @endif
            <div class="table-responsive-xl">
                <table class="table table-dark" id="studentTable">
                    <thead>
                        <tr>
                            <th scope="col">Learn Day</th>
                            <th scope="col">Learn Day date</th>
                            <th scope="col">Actions</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($learndays as $learnday)
                            <tr class="">
                                <td scope="row">{{ $learnday->title }}</td>
                                <td>{{ $learnday->date }}</td>
                                <td>{{ $learnday->course->name }}</td>
                                <td>
                                    <form action="{{ route('learndays.edit', $learnday) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-warning">Edit</button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{{ route('learndays.destroy', $learnday) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                                <td>

                                    <form action="{{ route('learndays.show', $learnday) }}" method="GET">
                                        @csrf
                                        <button type="submit" class="btn btn-info">Show data</button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>

@endsection

resources/views/learndays/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col"></div>
    <div class="col">
        <div class="card border-secondary bg-dark">
            <div class="card-body text-white">
                <h4 class="card-title">{{$learndays->title}}</h4>
                <p>Name of the Student: {{$learndays->title}}</p>
                <p>Birth of the Student: {{$learndays->date}}</p>
                <p>Class of the Student: {{$learndays->course->name}}</p>    
                
                
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>

@endsection

resources/views/learndays/show_deleted.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h1>Deleted Learn Day(s)</h1>
            <div class="table-responsive-xl">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th scope="col">Learn Day title</th>
                            <th scope="col">Date</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach ($learndays as $item)
                            <tr class="">
                                <td scope="row">{{$item->title}}</td>
                                <td>{{$item->date}}</td>
                                <td>
                                    <form action="{{ route('learndays.restore', $item) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn btn-info">Restore</button>
                                    </form>                                    
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>
@endsection